version: '3'
services:
  web:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./docker/conf.d:/etc/nginx/conf.d
  php:
    build:
      context: .
      dockerfile: ./docker/PHP.Dockerfile
    volumes:
      - .:/app
      - database:/app/var/data/

volumes:
  database: {}

