version: '3'
services:
  web:
    image: nginx:alpine
    ports: 
      - "80:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
  php:
    build:
      context: .
      dockerfile: ./docker/PHP.Dockerfile
    volumes:
      - .:/app
      - database:/app/var/data/

volumes:
  database: {}

